<aside class="Contact">
  <ul class="u-md-flex u-lg-flex">
    <li class="Contact-listItem u-md-size1of2 u-lg-size1of2">
      <p>
        <a class="Contact-link" href="https://www.thepetitionsite.com/950/133/872/save-grove-hill/">
          <span class="Contact-linkTitle">Sign</span>
          <br>
          <span>the petition</span>
        </a>
      </p>
    </li>
<!--
    <li class="Contact-listItem u-md-size1of3 u-lg-size1of3">
      <p>
        <a class="Contact-link" href="#relative#contribute/">
          <span class="Contact-linkTitle">Contribute</span>
          <br>
          <span>to Save Grove Hill</span>
        </a>
      </p>
    </li>
 -->
    <li class="Contact-listItem u-md-size1of2 u-lg-size1of2">
      <p>
        <a class="Contact-link" href="mailto:savegrovehill@gmail.com">
          <span class="Contact-linkTitle">Contact</span>
          <br>
          <span>savegrovehill@gmail.com</span>
        </a>
      </p>
    </li>
  </ul>
</aside>
