<aside class="Contact u-md-flex u-lg-flex">
  <div class="u-md-size1of3 u-lg-size1of3">
    <p>
      <a href="https://www.thepetitionsite.com/950/133/872/save-grove-hill/">
        <span style="color:gold;font-size:40px;font-style:italic;font-weight:900">Sign</span><br>
        <span style="color:white;font-size:16px;font-style:italic;font-weight:900">the petition</span>
      </a>
    </p>
  </div>
  <div class="u-md-size1of3 u-lg-size1of3">
    <p>
      <a href="#relative#contribute/">
        <span style="color:gold;font-size:40px;font-style:italic;font-weight:900">Contribute</span><br>
        <span style="color:white;font-size:16px;font-style:italic;font-weight:900">to Save Grove Hill</span>
      </a>
    </p>
  </div>
  <div class="u-md-size1of3 u-lg-size1of3">
    <p>
      <a href="mailto:savegrovehill@gmail.com" style="color:white">
        <span style="color:gold;font-size:40px;font-style:italic;font-weight:900">Contact</span><br>
        <span style="color:white;font-size:16px;font-style:italic;font-weight:900">savegrovehill@gmail.com</span>
      </a>
    </p>
  </div>
</aside>
