<footer class="Footer u-md-flex u-lg-flex u-md-flexJustifyBetween u-lg-flexJustifyBetween">
  <p class="Footer-social">
    <a href="https://www.instagram.com/" style="margin-right:2em">Facebook</a>
    <a href="https://www.instagram.com/savegrovehill/" style="margin-right:2em">Instagram</a>
    <a href="https://twitter.com/SaveGroveHill" style="margin-right:2em">Twitter</a>
  </p>
  <p class="Footer-legal">
    <span class="u-textNoWrap">Copyright © 2020 Save Grove Hill.</span> <span class="u-textNoWrap">All rights reserved.</span>
  </p>
</footer>
