<footer class="Footer">
  <nav class="u-flex">
    <ol class="u-size1of3">
      <li class="Footer-navListItem"><a class="Footer-link" href="#relative#">Home</a></li>
      <!-- <li class="Footer-navListItem"><a class="Footer-link" href="#relative#about/">About</a></li> -->
      <li class="Footer-navListItem"><a class="Footer-link" href="#relative#press/">Press</a></li>
      <li class="Footer-navListItem"><a class="Footer-link" href="#relative#documents/">Documents</a></li>
      <li class="Footer-navListItem"><a class="Footer-link" href="#relative#meetings/">Meetings</a></li>
      <li class="Footer-navListItem"><a class="Footer-link" href="#relative#ordinances/">Ordinances</a></li>
      <!-- <li class="Footer-navListItem"><a class="Footer-link" href="#relative#river-walk/">River Walk</a></li> -->
    </ol>
    <ol class="u-size1of3">
      <li class="Footer-navListItem"><a class="Footer-link" href="https://www.instagram.com/">Facebook</a></li>
      <li class="Footer-navListItem"><a class="Footer-link" href="https://www.instagram.com/savegrovehill/">Instagram</a></li>
      <li class="Footer-navListItem"><a class="Footer-link" href="https://twitter.com/SaveGroveHill">Twitter</a></li>
    </ol>
  </nav>
  <div>
    <p>
      <span class="u-textNoWrap">Copyright © 2020 Save Grove Hill.</span> <span class="u-textNoWrap">All rights reserved.</span>
    </p>
  </div>
</footer>
