<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-153726101-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-153726101-1');
  </script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="twitter:card" content="summary_large_image">
  <meta property="og:url" content="https://savegrovehill.org/">
  <meta property="og:title" content="Save Grove Hill">
  <meta property="og:description" content="">
  <meta property="og:image" content="#relative#documents/Preview%20Package.jpg">
  <title>#PAGE_TITLE# | Save Grove Hill</title>
  <link href="https://fonts.googleapis.com/css?family=Courier+Prime:400,700|Rubik:700&display=swap" rel="stylesheet">
  <link href="#relative#css/suitcss.css" rel="stylesheet">
  <link href="#relative#css/style.css" rel="stylesheet">
</head>
