<header class="Header" role="banner">
  <div class="Header-name">
    <a class="Header-link is-current" href="#relative#">
      Save Grove Hill
    </a>
  </div>
  <nav class="Header-nav">
    <ol class="Header-navList">
      <li class="Header-navListItem"><a class="Header-link#HOME_PAGE#" href="#relative#">Home</a></li>
      <!-- <li class="Header-navListItem"><a class="Header-link#ABOUT_PAGE#" href="#relative#about/">About</a></li> -->
      <li class="Header-navListItem"><a class="Header-link#DOCUMENTS_PAGE#" href="#relative#documents/">Documents</a></li>
      <li class="Header-navListItem"><a class="Header-link#MEETINGS_PAGE#" href="#relative#meetings/">Meetings</a></li>
      <li class="Header-navListItem"><a class="Header-link#ORDINANCES_PAGE#" href="#relative#ordinances/">Ordinances</a></li>
      <li class="Header-navListItem"><a class="Header-link#PRESS_PAGE#" href="#relative#press/">Press</a></li>
      <li class="Header-navListItem"><a class="Header-link#RIVERWALK_PAGE#" href="#relative#river-walk/">River Walk</a></li>
    </ol>
  </nav>
  <details class="Header-details">
    <summary class="Header-summary">Menu</summary>
    <nav class="Header-mobileNav">
      <ol class="Header-mobileNavList">
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink#HOME_PAGE#" href="#relative#">Home</a></li>
        <!-- <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink#ABOUT_PAGE#" href="#relative#about/">About</a></li> -->
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink#DOCUMENTS_PAGE#" href="#relative#documents/">Documents</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink#MEETINGS_PAGE#" href="#relative#meetings/">Meetings</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink#ORDINANCES_PAGE#" href="#relative#ordinances/">Ordinances</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink#PRESS_PAGE#" href="#relative#press/">Press</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink#RIVERWALK_PAGE#" href="#relative#river-walk/">River Walk</a></li>
      </ol>
    </nav>
  </details>
</header>
