<header class="Header" role="banner">
  <a class="Header-link is-current" href="#relative#">
    Save Grove Hill
  </a>
  <nav class="Header-nav">
    <ol class="Header-navList">
      <li><a class="Header-link #HOME_PAGE#" href="#relative#">Home</a></li>
      <!-- <li><a class="Header-link #ABOUT_PAGE#" href="#relative#about/index.html">About</a></li> -->
      <li><a class="Header-link #NEWS_PAGE#" href="#relative#news/index.html">News</a></li>
      <li><a class="Header-link #DOCUMENTS_PAGE#" href="#relative#documents/index.html">Documents</a></li>
      <li><a class="Header-link #MEETINGS_PAGE#" href="#relative#meetings/index.html">Meetings</a></li>
      <li><a class="Header-link #ORDINANCES_PAGE#" href="#relative#ordinances/index.html">Ordinances</a></li>
      <li><a class="Header-link #RIVERWALK_PAGE#" href="#relative#river-walk/index.html">River Walk</a></li>
      <li><a class="Header-link #CONTACT_PAGE#" href="#relative#contact/index.html">Contact</a></li>
    </ol>
  </nav>
  <details class="Header-details">
    <summary class="Header-summary">Menu</summary>
    <nav class="Header-mobileNav">
      <ol class="Header-mobileNavList">
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #HOME_PAGE#" href="#relative#">Home</a></li>
        <!-- <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #ABOUT_PAGE#" href="#relative#about/index.html">About</a></li> -->
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #NEWS_PAGE#" href="#relative#news/index.html">News</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #DOCUMENTS_PAGE#" href="#relative#documents/index.html">Documents</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #MEETINGS_PAGE#" href="#relative#meetings/index.html">Meetings</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #ORDINANCES_PAGE#" href="#relative#ordinances/index.html">Ordinances</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #RIVERWALK_PAGE#" href="#relative#river-walk/index.html">River Walk</a></li>
        <li class="Header-mobileNavListItem"><a class="Header-mobileNavlink #CONTACT_PAGE#" href="#relative#contact/index.html">Contact</a></li>
      </ol>
    </nav>
  </details>
</header>
